### ISSUE TITLE
Focus BG Color of Textarea

### ISSUE THREAD

**Issue by ztnel** [cSDes1gn/masterbomb#12]
See below. The text area focus bg color should be darker black to match the input text fields however I am unable to use the same css for textarea:
```css
input[type=text]:focus, textarea:focus{
  outline: 2px solid rgb(95, 182, 197);
  color: azure;
  background-color:rgb(23, 26, 29);
}
```

![Screen Shot 2021-04-24 at 9 56 30 PM](https://user-images.githubusercontent.com/26971036/115977660-eea53e80-a547-11eb-8576-06438721232b.png)
